name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release:
    uses: GEWIS/actions/.github/workflows/docker-release.yml@v1
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: "['.']"
      version: ${{ needs.versioning.outputs.next-version }}
      docker-registry: 'cbc.docker-registry.gewis.nl'
      docker-paths: "['custommailcow-ldap']"
      github-registry: 'true'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_CBC_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_CBC_PWD }}
